import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PW_PATH)
const url = process.argv[2] || 'http://127.0.0.1:5400/'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] })
const errs = []
const hook = (p) => { p.on('pageerror', (e) => errs.push('pageerror ' + e.message)); p.on('console', (m) => m.type() === 'error' && !/404/.test(m.text()) && errs.push(m.text().slice(0, 160))) }
const ok = (c, m) => console.log(c ? 'PASS' : 'FAIL', m)
// desktop
let ctx = await b.newContext({ viewport: { width: 1440, height: 900 } }); let p = await ctx.newPage(); hook(p)
await p.goto(url, { waitUntil: 'load' }); await p.waitForTimeout(3500)
await p.getByRole('button', { name: /book appointment/i }).first().click(); await p.waitForTimeout(1000)
ok(await p.getByRole('dialog', { name: /book/i }).isVisible(), 'hero CTA opens booking')
await p.getByRole('button', { name: 'Royal Package', exact: true }).click()
ok((await p.getByRole('button', { name: 'Royal Package', exact: true }).getAttribute('aria-pressed')) === 'true', 'service chip selects')
await p.fill('input[name=name]', 'Alex'); await p.fill('input[name=phone]', '+380000'); await p.fill('input[name=date]', '2026-12-01'); await p.selectOption('select[name=time]', '12:00')
await p.getByRole('button', { name: /request appointment/i }).click(); await p.waitForTimeout(600)
ok(await p.getByText(/See you in/).isVisible(), 'booking submit → confirmation')
await p.keyboard.press('Escape'); await p.waitForTimeout(1800)
ok(!(await p.getByRole('dialog').count()), 'Escape closes booking')
await p.getByRole('link', { name: 'Work' }).first().click(); await p.waitForTimeout(2500)
ok(Math.abs(await p.evaluate(() => document.querySelector('#work').getBoundingClientRect().top)) < 40, 'nav link jumps to section')
await p.getByRole('button', { name: /View project: The Gentleman Taper/ }).click(); await p.waitForTimeout(1500)
ok(await p.getByRole('dialog', { name: /gentleman/i }).isVisible(), 'project view opens')
await p.screenshot({ path: 'tools/out/qa_project.png' })
await p.getByRole('button', { name: 'Next project' }).click(); await p.waitForTimeout(1200)
ok(await p.getByRole('dialog', { name: /sharp line/i }).isVisible(), 'next project')
await p.getByRole('button', { name: 'Close project' }).click(); await p.waitForTimeout(1200)
ok(!(await p.getByRole('dialog').count()), 'project closes')
await p.evaluate(() => document.querySelector('[aria-label="Client reviews"]').scrollIntoView()); await p.waitForTimeout(1500)
const idx = () => p.evaluate(() => +document.querySelector('[aria-label="Client reviews"] .tabular-nums').textContent.trim().slice(0, 2))
const before = await idx()
await p.getByRole('button', { name: 'Next review' }).click(); await p.waitForTimeout(1500)
ok((await idx()) === (before % 4) + 1, 'testimonial next')
await p.evaluate(() => document.querySelector('#services').scrollIntoView()); await p.waitForTimeout(1500)
await p.getByRole('button', { name: /Book Beard Sculpt/ }).click(); await p.waitForTimeout(1000)
ok((await p.getByRole('button', { name: 'Beard Sculpt', exact: true }).getAttribute('aria-pressed')) === 'true', 'service row opens booking preselected')
await ctx.close()
// mobile
ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true }); p = await ctx.newPage(); hook(p)
await p.goto(url, { waitUntil: 'load' }); await p.waitForTimeout(3500)
await p.getByRole('button', { name: 'Open menu' }).tap(); await p.waitForTimeout(1200)
ok(await p.getByRole('dialog', { name: 'Menu' }).isVisible(), 'mobile menu opens'); await p.screenshot({ path: 'tools/out/qa_menu.png' })
await p.getByRole('dialog', { name: 'Menu' }).getByRole('link', { name: /Team/ }).tap(); await p.waitForTimeout(2500)
ok(Math.abs(await p.evaluate(() => document.querySelector('#team').getBoundingClientRect().top)) < 40, 'mobile menu link navigates')
await p.evaluate(() => document.querySelector('#services').scrollIntoView()); await p.waitForTimeout(1200)
await p.getByRole('button', { name: /Beard Sculpt, 40/ }).tap(); await p.waitForTimeout(900)
ok(await p.getByRole('button', { name: /Book this/ }).first().isVisible(), 'mobile service expands')
ok(!(await p.locator('.has-cursor').count()), 'no custom cursor on touch')
await ctx.close()
// reduced motion
ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' }); p = await ctx.newPage(); hook(p)
await p.goto(url, { waitUntil: 'load' }); await p.waitForTimeout(2500)
ok(!(await p.getByRole('status').count()), 'reduced motion: no preloader'); await p.screenshot({ path: 'tools/out/qa_rm.png' })
await ctx.close(); await b.close()
console.log(errs.length ? 'ERRORS:\n' + [...new Set(errs)].join('\n') : 'no console errors')
